// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview AI flow to suggest breeds from a photo of a pet.
 *
 * - suggestBreedsFromPhoto - A function that suggests possible breeds based on the image.
 * - SuggestBreedsFromPhotoInput - The input type for the suggestBreedsFromPhoto function.
 * - SuggestBreedsFromPhotoOutput - The return type for the suggestBreedsFromPhoto function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestBreedsFromPhotoInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo of a pet, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type SuggestBreedsFromPhotoInput = z.infer<typeof SuggestBreedsFromPhotoInputSchema>;

const SuggestBreedsFromPhotoOutputSchema = z.object({
  suggestedBreeds: z.array(z.string()).describe('An array of suggested breeds for the pet.'),
});
export type SuggestBreedsFromPhotoOutput = z.infer<typeof SuggestBreedsFromPhotoOutputSchema>;

export async function suggestBreedsFromPhoto(input: SuggestBreedsFromPhotoInput): Promise<SuggestBreedsFromPhotoOutput> {
  return suggestBreedsFromPhotoFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestBreedsFromPhotoPrompt',
  input: {schema: SuggestBreedsFromPhotoInputSchema},
  output: {schema: SuggestBreedsFromPhotoOutputSchema},
  prompt: `You are an expert in pet breeds.

  Based on the provided image, suggest possible breeds for the pet. Provide an array of breeds that are most likely for the given pet in the photo.

  Photo: {{media url=photoDataUri}}`,
});

const suggestBreedsFromPhotoFlow = ai.defineFlow(
  {
    name: 'suggestBreedsFromPhotoFlow',
    inputSchema: SuggestBreedsFromPhotoInputSchema,
    outputSchema: SuggestBreedsFromPhotoOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
