
export const allDogBreeds = [
  'Toy Poodle',
  'Maltipoo',
  'Pomeranian Boo',
  'Maltese Terrier',
  'Border Collie',
  'Cane Corso',
  'Doberman',
  'Golden Retriever',
  'Çin Aslanı',
  'Sibirya Kurdu (Husky)',
  'Chihuahua',
  'Labrador Retriever',
  'Alman Kurdu',
  'Cavalier King Charles',
  'Akita Inu',
  'Dakhund - Sosis Köpek',
  'Rottweiler',
  'Labradoodle',
  'Yorkshire Terrier',
  'Belçika Kurdu',
  'French Bulldog',
  'Morkie',
  'Pug',
  'Beagle',
  'Pekinez',
  'Samoyed',
  'Amerikan Cocker',
  'Shih Tzu',
  'Bernese Dağ Köpeği',
  'Jack Russell Terrier',
  'Goldendoodle',
  'İngiliz Bulldog',
  'İngiliz Cocker',
  'corgi',
  'Pincher',
  'Shiba Köpek',
  'Cockapoo',
  'Alabay (Alabai)',
  'Kangal',
  'bernedoodle',
  'Bişon Çuha Köpeği',
  'Wolfdog',
  'Cavapoo',
  'Schnauzer',
  'American Bully',
  'Avustralya Çoban Köpeği',
  'Saint Bernard',
  'Spitz',
  'Dalmaçyalı',
  'Danua (Great Dane)',
  'İngiliz Staffordshire',
  'Akbaş',
  'Alaska Kurdu',
  'Dogo Argentino',
  'Fransız Mastiff',
  'Havanese',
  'Kafkas Çoban Köpeği',
  'Lagotto Romagnolo',
  'Newfoundland Köpek',
  'Pitbull',
  'Süs Köpeği',
  'Tibet Mastifi'
];

export const allCatBreeds = [
  'British Shorthair',
  'Scottish Fold',
  'Tekir',
  'British Longhair',
  'Maine Coon',
  'Sfenks Kedisi',
  'İran Kedisi',
  'Scottish Straight',
  'Scottish Fold Longhair',
  'Ankara Kedisi',
  'Chinchilla',
  'Exotic Shorthair',
  'Munchkin Kedisi',
  'Ragdoll Kedisi',
  'Sarman Kedi',
  'Siyam',
  'Van Kedisi'
];

export const allBirdBreeds = [
    "Muhabbet Kuşu",
    "Sultan Papağanı",
    "Papağan",
    "Kanarya",
    "Hint Bülbülü",
    "Cennet Papağanı",
    "Forpus Papağanı"
];

export const allAquariumBreeds = [
    "Japon Balığı",
    "Lepistes",
    "Beta",
    "Melek Balığı",
    "Ciklet",
    "Vatoz",
    "Neon Tetra",
    "Discus",
    "Moli",
    "Kılıçkuyruk",
    "Karides"
];

export const allOtherBreeds = [
    "Hamster",
    "Tavşan",
    "Guineapig",
    "Kaplumbağa",
    "Iguana"
];
