
export const allDogBreeds = [
  'Toy Poodle',
  'Maltipoo',
  'Pomeranian Boo',
  'Maltese Terrier',
  'Border Collie',
  'Cane Corso',
  'Doberman',
  'Golden Retriever',
  'Çin Aslanı',
  'Sibirya Kurdu (Husky)',
  'Chihuahua',
  'Labrador Retriever',
  'Alman Kurdu',
  'Cavalier King Charles',
  'Akita Inu',
  'Dakhund - Sosis Köpek',
  'Rottweiler',
  'Labradoodle',
  'Yorkshire Terrier',
  'Belçika Kurdu',
  'French Bulldog',
  'Morkie',
  'Pug',
  'Beagle',
  'Pekinez',
  'Samoyed',
  'Amerikan Cocker',
  'Shih Tzu',
  'Bernese Dağ Köpeği',
  'Jack Russell Terrier',
  'Goldendoodle',
  'İngiliz Bulldog',
  'İngiliz Cocker',
  'Corgi',
  'Pincher',
  'Shiba Köpek',
  'Cockapoo',
  'Alabay (Alabai)',
  'Kangal',
  'Bernedoodle',
  'Bişon Çuha Köpeği',
  'Wolfdog',
  'Cavapoo',
  'Schnauzer',
  'American Bully',
  'Avustralya Çoban Köpeği',
  'Saint Bernard',
  'Spitz',
  'Dalmaçyalı',
  'Danua (Great Dane)',
  'İngiliz Staffordshire',
  'Akbaş',
  'Alaska Kurdu',
  'Dogo Argentino',
  'Fransız Mastiff',
  'Havanese',
  'Kafkas Çoban Köpeği',
  'Lagotto Romagnolo',
  'Newfoundland Köpek',
  'Pitbull',
  'Süs Köpeği',
  'Tibet Mastifi',
  'Affenpinscher',
  'Afghan Hound',
  'Airedale Terrier',
  'Akita',
  'Alaskan Malamute',
  'American Bulldog',
  'American Eskimo Dog',
  'American Foxhound',
  'American Staffordshire Terrier',
  'Anatolian Shepherd Dog',
  'Australian Cattle Dog',
  'Australian Shepherd',
  'Basenji',
  'Basset Hound',
  'Bearded Collie',
  'Bedlington Terrier',
  'Belgian Malinois',
  'Belgian Sheepdog',
  'Belgian Tervuren',
  'Bernese Mountain Dog',
  'Bichon Frise',
  'Black and Tan Coonhound',
  'Bloodhound',
  'Borzoi',
  'Boston Terrier',
  'Bouvier des Flandres',
  'Boxer',
  'Briard',
  'Brittany',
  'Brussels Griffon',
  'Bull Terrier',
  'Bulldog',
  'Bullmastiff',
  'Cairn Terrier',
  'Canaan Dog',
  'Cardigan Welsh Corgi',
  'Cavalier King Charles Spaniel',
  'Chesapeake Bay Retriever',
  'Chinese Crested',
  'Chinese Shar-Pei',
  'Chow Chow',
  'Clumber Spaniel',
  'Cocker Spaniel',
  'Collie',
  'Coton de Tulear',
  'Dachshund',
  'Dalmatian',
  'Doberman Pinscher',
  'English Cocker Spaniel',
  'English Setter',
  'English Springer Spaniel',
  'English Toy Spaniel',
  'Entlebucher Mountain Dog',
  'Field Spaniel',
  'Finnish Lapphund',
  'Finnish Spitz',
  'Flat-Coated Retriever',
  'Fransız Bulldog',
  'German Pinscher',
  'German Shepherd',
  'German Shorthaired Pointer',
  'German Wirehaired Pointer',
  'Giant Schnauzer',
  'Glen of Imaal Terrier',
  'Gordon Setter',
  'Great Dane',
  'Great Pyrenees',
  'Greater Swiss Mountain Dog',
  'Greyhound',
  'Ibizan Hound',
  'Icelandic Sheepdog',
  'Irish Red and White Setter',
  'Irish Setter',
  'Irish Terrier',
  'Irish Water Spaniel',
  'Irish Wolfhound',
  'Italian Greyhound',
  'Japanese Chin',
  'Keeshond',
  'Kerry Blue Terrier',
  'Komondor',
  'Kuvasz',
  'Lakeland Terrier',
  'Leonberger',
  'Lhasa Apso',
  'Lowchen',
  'Maltese',
  'Manchester Terrier',
  'Mastiff',
  'Miniature Bull Terrier',
  'Miniature Pinscher',
  'Miniature Schnauzer',
  'Neapolitan Mastiff',
  'Newfoundland',
  'Norfolk Terrier',
  'Norwegian Buhund',
  'Norwegian Elkhound',
  'Norwegian Lundehund',
  'Norwich Terrier',
  'Nova Scotia Duck Tolling Retriever',
  'Old English Sheepdog',
  'Otterhound',
  'Papillon',
  'Parson Russell Terrier',
  'Pekingese',
  'Pembroke Welsh Corgi',
  'Petit Basset Griffon Vendeen',
  'Pharaoh Hound',
  'Plott',
  'Pointer',
  'Pomeranian',
  'Poodle',
  'Portuguese Water Dog',
  'Puli',
  'Pyrenean Shepherd',
  'Rat Terrier',
  'Redbone Coonhound',
  'Rhodesian Ridgeback',
  'Saint Bernard',
  'Saluki',
  'Schipperke',
  'Scottish Deerhound',
  'Scottish Terrier',
  'Sealyham Terrier',
  'Shetland Sheepdog',
  'Shiba Inu',
  'Siberian Husky',
  'Silky Terrier',
  'Sivas Kangalı',
  'Skye Terrier',
  'Smooth Fox Terrier',
  'Soft Coated Wheaten Terrier',
  'Staffordshire Bull Terrier',
  'Standard Schnauzer',
  'Sussex Spaniel',
  'Swedish Vallhund',
  'Tibetan Spaniel',
  'Tibetan Terrier',
  'Toy Fox Terrier',
  'Treeing Walker Coonhound',
  'Vizsla',
  'Weimaraner',
  'Welsh Springer Spaniel',
  'Welsh Terrier',
  'West Highland White Terrier',
  'Whippet',
  'Wire Fox Terrier',
  'Wirehaired Pointing Griffon',
  'Xoloitzcuintli'
];

export const allCatBreeds = [
  'Abyssinian',
  'American Bobtail',
  'American Curl',
  'American Shorthair',
  'American Wirehair',
  'Ankara Kedisi',
  'Balinese',
  'Bengal',
  'Birman',
  'Bombay',
  'British Longhair',
  'British Shorthair',
  'Burmese',
  'Burmilla',
  'Chartreux',
  'Chausie',
  'Cornish Rex',
  'Devon Rex',
  'Egyptian Mau',
  'Exotic Shorthair',
  'Havana Brown',
  'Himalayan',
  'Japanese Bobtail',
  'Korat',
  'LaPerm',
  'Maine Coon',
  'Manx',
  'Nebelung',
  'Norwegian Forest Cat',
  'Ocicat',
  'Oriental',
  'Persian',
  'Ragamuffin',
  'Ragdoll',
  'Russian Blue',
  'Sarman',
  'Savannah',
  'Scottish Fold',
  'Selkirk Rex',
  'Siamese',
  'Siberian',
  'Singapura',
  'Siyam',
  'Somali',
  'Sphynx',
  'Tekir',
  'Tonkinese',
  'Turkish Angora',
  'Turkish Van',
  'Van Kedisi',
];
