/**
 * FIRESTORE DATABASE SCHEMA DOCUMENTATION
 * =======================================
 * 
 * Bu dosya Firestore'daki veri yapısını tanımlar.
 * Tüm componentler bu şemayı takip etmelidir.
 */

/**
 * COLLECTION: /users
 * PURPOSE: Tüm kullanıcı profillerini saklar
 * DOCUMENT ID: Firebase Auth UID
 * 
 * ÖRNEK PATH: /users/user123abc
 * 
 * FIELDS:
 * {
 *   id: string                 // UID ile aynı olmalı
 *   name: string               // Kullanıcı adı
 *   email: string              // E-mail
 *   phoneNumber: string        // İsteğe bağlı
 *   location: string           // İsteğe bağlı
 *   userStatus: 'normal' | 'premium' | 'onayli' | 'yasakli'
 *   credit: number             // Premium puan
 *   createdAt: timestamp       // Oluşturulma tarihi
 *   updatedAt: timestamp       // Güncellenme tarihi
 * }
 */

/**
 * SUBCOLLECTION: /users/{userId}/petListings
 * PURPOSE: Belirli bir kullanıcının hayvan ilanlarını saklar
 * DOCUMENT ID: Auto-generated by Firestore (addDoc)
 * 
 * ÖRNEK PATH: /users/user123abc/petListings/listing456def
 * 
 * FIELDS:
 * {
 *   id: string                    // Otomatik üretilir
 *   userId: string                // KRITIK! Üst path'in user ID'siyle aynı olmalı
 *   species: 'Dog' | 'Cat' | 'Bird' | 'Aquarium' | 'Other'
 *   breed: string                 // Köpek/Kedi cinsi
 *   name: string                  // Hayvanın adı
 *   age: string                   // Yaş (ör: "2 years")
 *   location: string              // Konum
 *   description: string           // İlan açıklaması
 *   imageUrl: string              // Firebase Storage'daki görsel URL
 *   listingType: 'Adoption' | 'Sale'
 *   price: number                 // İsteğe bağlı, satışsa fiyat
 *   isFeatured: boolean           // Ön plana çıkarılmış mı?
 *   createdAt: timestamp
 *   updatedAt: timestamp
 * }
 */

/**
 * SUBCOLLECTION: /users/{userId}/services
 * PURPOSE: Kullanıcı tarafından sağlanan hizmetleri saklar
 * DOCUMENT ID: Auto-generated
 * 
 * ÖRNEK PATH: /users/user123abc/services/service789ghi
 * 
 * FIELDS:
 * {
 *   id: string
 *   userId: string              // KRITIK! Üst path'in user ID'siyle aynı
 *   name: string                // Hizmet adı (ör: "Dr. Ahmet Vetiner Kliniği")
 *   type: 'Veterinarian' | 'Pet Hotel' | 'Trainer' | 'Groomer' | 'Pet Taxi' | 'Petshop' | 'Walker'
 *   description: string
 *   address: string             // Hizmet yeri adresi
 *   phoneNumber: string
 *   websiteUrl: string          // İsteğe bağlı
 *   createdAt: timestamp
 *   updatedAt: timestamp
 * }
 */