import type { DemoIlan } from './tipler';

/**
 * Demo ilanlar — her kategoride dört tane.
 *
 * Metinler gerçek bir ilan gibi yazıldı: sahibi neyi neden verdiğini
 * anlatıyor, hayvanın huyunu ve sağlık durumunu söylüyor. Şablondan
 * üretilmiş "Satılık yavru, detay için arayınız" tarzı satırlar vitrini
 * doldurmaz, boş gösterir.
 *
 * Satılık ilanlar yalnızca kurumsal hesaplarda. Bu bir tercih değil,
 * sitenin kendi kuralı: 5199 sayılı kanun gereği bireysel hesaplar hayvan
 * satamıyor ve veritabanı bunu tetikleyiciyle engelliyor. Güvercin ve
 * malzeme bu kuralın dışında, o yüzden oralarda bireysel satış var.
 */
export const DEMO_ILANLAR: DemoIlan[] = [
  // --- Köpek ---
  {
    slug: 'golden-yavru-yuva-ariyor',
    kullanici: 'elif',
    kategori: 'kopek-ilanlari',
    cins: 'golden-retriever',
    kind: 'sahiplendirme',
    baslik: 'Golden yavrumuz için yuva arıyoruz',
    aciklama:
      'Komşumuzun köpeği doğurdu, dört yavrudan biri bizde kaldı. Üç aylık, dişi. Karma aşısı yapıldı, iç ve dış parazit uygulaması tamam, aşı karnesi mevcut. Çocuklarla çok iyi anlaşıyor, tuvalet eğitimi başladı ve gazete üzerine yapıyor.\n\nApartmanda büyüdü ama Golden’ın günde en az bir saat hareket istediğini bilerek sahiplenmenizi rica ediyoruz. Bahçeli ev şart değil, düzenli yürüyüş yeterli. Yuva görmek isterim, aramızda irtibat kopmasın istiyorum.',
    yasAy: 3,
    cinsiyet: 'disi',
    boyut: 'buyuk',
    renk: 'Krem',
    asili: true,
    icParazit: true,
    disParazit: true,
    sehir: 'istanbul',
    ilce: 'kadikoy',
    gorselTerimleri: ['Category:Golden Retriever puppies', 'Category:Golden Retriever', 'Golden Retriever puppy'],
  },
  {
    slug: 'kangal-yavrulari-sivas',
    kullanici: 'anadolu',
    kategori: 'kopek-ilanlari',
    cins: 'kangal',
    kind: 'satilik',
    baslik: 'Şecereli Kangal yavruları — anne baba görülebilir',
    aciklama:
      'Tesisimizde doğan Kangal yavruları. İki buçuk aylık, üç erkek iki dişi. Anne ve baba yerinde görülebilir; ikisi de sürü başında çalışan hatlardan.\n\nYavrular karma aşılarını oldu, mikroçipleri takıldı ve kayıtları yapıldı. Şecere belgesi teslimde veriliyor. Kangal apartman köpeği değil; geniş alanı ve iş verebilecek sahipler için uygundur. Tesisimizi görmeye gelmenizi öneririz, yavruyu annesiyle birlikte göstermek istiyoruz.',
    fiyat: 18000,
    pazarlik: true,
    yasAy: 2,
    cinsiyet: 'erkek',
    boyut: 'dev',
    renk: 'Boz',
    asili: true,
    icParazit: true,
    disParazit: true,
    secere: true,
    mikrocip: true,
    saglikRaporu: true,
    sehir: 'sivas',
    ilce: 'merkez',
    gorseller: ['Kangal front on.jpg'],
    fotografSayisi: 1,
    gorselTerimleri: ['Category:Kangal Shepherd Dog', 'Category:Anatolian Shepherd Dog', 'Kangal Shepherd Dog'],
  },
  {
    slug: 'pomeranian-boo-yavru',
    kullanici: 'egekatteri',
    kategori: 'kopek-ilanlari',
    cins: 'pomeranian-boo',
    kind: 'satilik',
    baslik: 'Pomeranian yavru — aşıları tam, sağlık raporlu',
    aciklama:
      'Üç aylık Pomeranian yavrumuz yeni ailesini bekliyor. Karma ve kuduz aşıları yapıldı, veteriner sağlık raporu ve aşı karnesi teslim ediliyor.\n\n“Boo” diye bilinen görünüm ayrı bir ırk değil, tüyün kısa traş edilmiş hâlidir; yavrumuz doğal tüyüyle teslim ediliyor. Küçük ırklarda soluk borusu hassasiyeti olduğu için boyun tasması yerine göğüs tasması kullanılmasını öneriyoruz. Yavruyu görmek isteyenleri işletmemize bekliyoruz.',
    fiyat: 22000,
    yasAy: 3,
    cinsiyet: 'disi',
    boyut: 'mini',
    renk: 'Turuncu',
    asili: true,
    icParazit: true,
    disParazit: true,
    saglikRaporu: true,
    mikrocip: true,
    sehir: 'izmir',
    ilce: 'karsiyaka',
    gorseller: ['Pomeranian.JPG'],
    fotografSayisi: 1,
    gorselTerimleri: ['Category:Pomeranian (dog)', 'Category:Pomeranian dogs', 'Pomeranian dog'],
  },
  {
    slug: 'sokakta-bulunan-melez-yavru',
    kullanici: 'burak',
    kategori: 'kopek-ilanlari',
    cinsDiger: 'Melez',
    kind: 'sahiplendirme',
    baslik: 'Sokakta bulduğum melez yavru yuva arıyor',
    aciklama:
      'Sanayi bölgesinde tek başına dolaşırken buldum, yaklaşık dört aylık. Veterinere götürdüm; iç ve dış parazit uygulaması yapıldı, karma aşısının ilk dozu vuruldu, ikinci doz için tarih verildi.\n\nÇok uysal, elden yemek alıyor, kucağa alınmaya alışkın. Diğer köpeklerle sorunu yok. Şu anda geçici olarak bende kalıyor ama uzun süre bakamam. Orta boy olacak gibi duruyor. Kısırlaştırma sözü veren, yuva gösteren sahiplerle görüşmek isterim.',
    yasAy: 4,
    cinsiyet: 'erkek',
    boyut: 'orta',
    renk: 'Siyah beyaz',
    icParazit: true,
    disParazit: true,
    sehir: 'bursa',
    ilce: 'nilufer',
    gorselTerimleri: ['Category:Mongrel dogs', 'Category:Mixed-breed dogs', 'Mongrel dog'],
  },

  // --- Kedi ---
  {
    slug: 'british-shorthair-yavru-izmir',
    kullanici: 'egekatteri',
    kategori: 'kedi-ilanlari',
    cins: 'british-shorthair',
    kind: 'satilik',
    baslik: 'British Shorthair yavru — anne baba HCM taramalı',
    aciklama:
      'Katterimizde doğan British Shorthair yavrular. Üç aylık, gri (blue) renkte. Anne ve babanın kalp taraması (HCM ekokardiyografi) yapıldı, sonuç belgeleri teslimde veriliyor.\n\nYavrular sekiz haftadan sonra anneden ayrıldı, kum eğitimi tamamlandı ve karma aşıları yapıldı. Mikroçip takıldı. Sakin bir ırktır, apartman yaşamına uygundur; buna karşılık kilo almaya yatkın olduğu için porsiyon kontrolü öneriyoruz. Katterimizi ziyaret edip yavruyu annesiyle görebilirsiniz.',
    fiyat: 25000,
    yasAy: 3,
    cinsiyet: 'erkek',
    renk: 'Gri (blue)',
    asili: true,
    icParazit: true,
    disParazit: true,
    secere: true,
    mikrocip: true,
    saglikRaporu: true,
    sehir: 'izmir',
    ilce: 'karsiyaka',
    gorseller: ['Britishblue.jpg'],
    fotografSayisi: 1,
    gorselTerimleri: ['Category:British Shorthair', 'Category:British Shorthair kittens', 'British Shorthair cat'],
  },
  {
    slug: 'tekir-yavru-sahiplendirme-bursa',
    kullanici: 'burak',
    kategori: 'kedi-ilanlari',
    cins: 'tekir',
    kind: 'sahiplendirme',
    baslik: 'İki tekir yavru birlikte yuva arıyor',
    aciklama:
      'Apartman bahçesinde doğan yavrulardan ikisi. Yaklaşık iki buçuk aylık, biri erkek biri dişi, kardeşler. Kum eğitimi tamamlandı, mama yiyorlar.\n\nVeteriner kontrolünden geçtiler; iç parazit uygulaması yapıldı, ilk aşıları için tarih verildi. Birbirlerine çok alışkın oldukları için mümkünse ikisini birlikte sahiplendirmek istiyoruz, ayrı ayrı da olabilir. Kısırlaştırma sözü veren sahiplerle görüşmek isterim.',
    yasAy: 2,
    cinsiyet: 'belirtilmemis',
    adet: 2,
    renk: 'Tekir',
    icParazit: true,
    sehir: 'bursa',
    ilce: 'nilufer',
    gorseller: ['Cat November 2010-1a.jpg'],
    fotografSayisi: 1,
    gorselTerimleri: ['Category:Tabby cats', 'Category:Kittens', 'Tabby kitten'],
  },
  {
    slug: 'scottish-fold-yavru-antalya',
    kullanici: 'egekatteri',
    kategori: 'kedi-ilanlari',
    cins: 'scottish-fold',
    kind: 'satilik',
    baslik: 'Scottish Fold yavru — eşleştirme fold × straight',
    aciklama:
      'Katterimizde doğan Scottish Fold yavru, üç aylık. Eşleştirme kıvrık kulaklı bir kedi ile dik kulaklı (Scottish Straight) bir kedi arasında yapıldı; iki kıvrık kulaklı kediyi asla eşleştirmiyoruz, çünkü iki kopya geni birden alan yavrularda eklem sorunları erken yaşta ve ağır seyrediyor.\n\nAynı batında dik kulaklı kardeşler de var, onlar da sahiplendirilecek. Karma aşı yapıldı, mikroçip takıldı, kum eğitimi tamam. Yavruyu yürürken ve atlarken izlemenizi, eklem hareketlerini kendi gözünüzle görmenizi öneriyoruz.',
    fiyat: 28000,
    yasAy: 3,
    cinsiyet: 'disi',
    renk: 'Krem',
    asili: true,
    icParazit: true,
    secere: true,
    mikrocip: true,
    saglikRaporu: true,
    sehir: 'antalya',
    ilce: 'muratpasa',
    gorseller: ['Adult Scottish Fold.jpg'],
    fotografSayisi: 1,
    gorselTerimleri: ['Category:Scottish Fold', 'Category:Scottish Fold cats', 'Scottish Fold cat'],
  },
  {
    slug: 'van-kedisi-yuva-ariyor',
    kullanici: 'elif',
    kategori: 'kedi-ilanlari',
    cins: 'van-kedisi',
    kind: 'sahiplendirme',
    baslik: 'Van kedisi — bir yaşında, kısırlaştırıldı',
    aciklama:
      'Bir yaşında dişi Van kedisi. Taşınma nedeniyle bakamayacak bir tanıdığımdan devraldım, şu anda bende kalıyor. Kısırlaştırıldı, karma ve kuduz aşıları tam, mikroçipi var.\n\nİki gözü de kehribar renginde. Sudan korkmuyor, lavaboda oynamayı seviyor. İnsana çok alışkın, kucağa geliyor. Evde başka kedi olmasında sorun yaşamadı. Kapalı yaşamaya alışkın; balkon filesi olan bir eve vermek istiyorum.',
    yasAy: 12,
    cinsiyet: 'disi',
    renk: 'Beyaz',
    asili: true,
    kisir: true,
    mikrocip: true,
    icParazit: true,
    sehir: 'van',
    ilce: 'ipekyolu',
    gorseller: ['VAN CAT.png'],
    fotografSayisi: 1,
    gorselTerimleri: ['Category:Turkish Van', 'Category:Turkish Van cats', 'Van cat'],
  },

  // --- Kuş ---
  {
    slug: 'sultan-papagani-cift',
    kullanici: 'kanatpet',
    kategori: 'kus-ilanlari',
    cins: 'sultan-papagani',
    kind: 'satilik',
    baslik: 'Sultan papağanı çift — elde büyütme',
    aciklama:
      'Elde büyütülmüş sultan papağanı çifti. Yaklaşık altı aylık, ele alışkınlar ve parmağa çıkıyorlar. Erkek olan ıslık öğrenmeye başladı.\n\nTohum ağırlıklı beslenme yerine pelet mama ve sebzeyle besliyoruz; alıştıkları karışımı yanında veriyoruz. Bu tür gece paniği yaşayabildiği için kafes yanında loş bir gece lambası bırakmanızı öneriyoruz. Kafes dahil değildir, isteyene uygun ölçüde kafes tedarik edebiliyoruz.',
    fiyat: 4500,
    yasAy: 6,
    cinsiyet: 'belirtilmemis',
    adet: 2,
    sehir: 'konya',
    ilce: 'selcuklu',
    gorseller: ['Cockatiel 3.jpg'],
    fotografSayisi: 1,
    gorselTerimleri: ['Category:Nymphicus hollandicus', 'Category:Cockatiels', 'Cockatiel bird'],
  },
  {
    slug: 'muhabbet-kusu-sahiplendirme',
    kullanici: 'zeynep',
    kategori: 'kus-ilanlari',
    cins: 'muhabbet-kusu',
    kind: 'sahiplendirme',
    baslik: 'Muhabbet kuşu ikilisi kafesiyle birlikte',
    aciklama:
      'İki muhabbet kuşu, birlikte büyüdüler ve ayrılmalarını istemiyorum. Yaklaşık iki yaşındalar, sağlıklılar. Kafes, yemlik, suluk, tünek ve mürekkep kemiği dahil veriyorum.\n\nEv değişikliği nedeniyle bakamayacağım. Sürü hâlinde yaşayan bir tür oldukları için tek başına kalmamaları önemli; bu yüzden ikisini birlikte sahiplenecek birini arıyorum. Ücret istemiyorum, sadece iyi bakılacaklarından emin olmak istiyorum.',
    yasAy: 24,
    cinsiyet: 'belirtilmemis',
    adet: 2,
    sehir: 'ankara',
    ilce: 'cankaya',
    gorseller: ['Wellensittich maennchen wildfarben.jpg'],
    fotografSayisi: 1,
    gorselTerimleri: ['Category:Melopsittacus undulatus', 'Category:Budgerigars', 'Budgerigar bird'],
  },
  {
    slug: 'kanarya-erkek-oten',
    kullanici: 'kanatpet',
    kategori: 'kus-ilanlari',
    cins: 'kanarya',
    kind: 'satilik',
    baslik: 'Öten erkek kanarya — bu yılın kuşu',
    aciklama:
      'Bu yıl çıkma erkek kanarya, ötüşü oturmuş durumda. Sarı renkte, tüyleri düzgün ve sağlıklı.\n\nKanarya sessiz bir ev kuşudur, muhabbet kuşuna göre daha az dağınıklık yapar. Ötüş için tek başına kafeste tutulması tercih edilir. Yem karışımı ve alıştığı yemlikle birlikte teslim ediyoruz. İşletmemize gelip kuşu ötüşüyle birlikte dinleyebilirsiniz.',
    fiyat: 2200,
    yasAy: 8,
    cinsiyet: 'erkek',
    renk: 'Sarı',
    sehir: 'konya',
    ilce: 'selcuklu',
    gorseller: ['Serinus canaria -Parque Rural del Nublo, Gran Canaria, Spain -male-8a.jpg'],
    fotografSayisi: 1,
    gorselTerimleri: ['Category:Serinus canaria domestica', 'Category:Domestic canary', 'Domestic canary bird'],
  },
  {
    slug: 'cennet-papagani-cift-sahiplendirme',
    kullanici: 'zeynep',
    kategori: 'kus-ilanlari',
    cins: 'cennet-papagani',
    kind: 'sahiplendirme',
    baslik: 'Cennet papağanı çifti yuva arıyor',
    aciklama:
      'İki cennet papağanı (love bird), birbirine çok bağlı bir çift. Yaklaşık bir buçuk yaşındalar. Sesli bir tür oldukları için apartmanda komşuyla sorun yaşayabilirsiniz, bunu baştan söylemek isterim.\n\nKafesleri, yemlikleri ve oyuncaklarıyla birlikte veriyorum. Yeni işim nedeniyle evde neredeyse hiç bulunamıyorum ve bu tür ilgi isteyen bir kuş. Ücret talep etmiyorum.',
    yasAy: 18,
    cinsiyet: 'belirtilmemis',
    adet: 2,
    sehir: 'ankara',
    ilce: 'cankaya',
    gorseller: ['Rosy-faced lovebird (Agapornis roseicollis roseicollis).jpg'],
    fotografSayisi: 1,
    gorselTerimleri: ['Category:Agapornis roseicollis', 'Category:Agapornis', 'Rosy-faced lovebird'],
  },

  // --- Akvaryum ---
  {
    slug: 'japon-baligi-genc',
    kullanici: 'akdenizpet',
    kategori: 'akvaryum-ilanlari',
    cins: 'japon-baligi',
    kind: 'satilik',
    baslik: 'Japon balığı — genç, sağlıklı, adetle',
    aciklama:
      'İşletmemizde yetişen genç japon balıkları. Karantina süresini tamamladılar, yüzgeç ve pul yapıları sağlam.\n\nJapon balığı yaygın sanılanın aksine küçük fanusta yaşayamıyor: çok atık üretiyor ve iyi bir filtre ile en az 50 litre alan istiyor. Bu bilgiyi baştan veriyoruz ki balık kısa sürede kaybedilmesin. Uygun akvaryum ve filtre için de yardımcı olabiliriz. Taşıma için oksijenli poşet hazırlıyoruz.',
    fiyat: 150,
    adet: 1,
    sehir: 'antalya',
    ilce: 'muratpasa',
    gorseller: ['Gold fish1.jpg'],
    fotografSayisi: 1,
    gorselTerimleri: ['Category:Carassius auratus auratus', 'Category:Goldfish', 'Goldfish aquarium'],
  },
  {
    slug: 'lepistes-yavrulari-fazla',
    kullanici: 'zeynep',
    kategori: 'akvaryum-ilanlari',
    cins: 'lepistes',
    kind: 'sahiplendirme',
    baslik: 'Lepistes yavruları fazla geldi, ücretsiz veriyorum',
    aciklama:
      'Akvaryumumdaki lepistesler çoğaldı, yer kalmadı. Yaklaşık yirmi yavru var, hepsi sağlıklı ve hareketli.\n\nLepistes başlangıç için en kolay türlerden biri: dayanıklı, ısı aralığı geniş, üremesi kolay. Yalnız çok hızlı çoğaldıkları için erkek-dişi oranını ayarlamanızı öneririm. Kendi kabınızı getirirseniz suyla birlikte veriyorum. Ücret istemiyorum.',
    adet: 20,
    sehir: 'ankara',
    ilce: 'cankaya',
    gorseller: ['Guppy pho 0048.jpg'],
    fotografSayisi: 1,
    gorselTerimleri: ['Category:Poecilia reticulata', 'Category:Guppies', 'Guppy aquarium fish'],
  },
  {
    slug: 'beta-erkek-renkli',
    kullanici: 'akdenizpet',
    kategori: 'akvaryum-ilanlari',
    cins: 'beta',
    kind: 'satilik',
    baslik: 'Beta (Siyam balığı) — erkek, renkli varyasyonlar',
    aciklama:
      'Erkek beta balıkları, farklı renk varyasyonlarında. Yüzgeçleri tam, aktif ve yem alıyorlar.\n\nErkek betalar birbirini kabul etmez; her erkek ayrı kapta tutulmalıdır. Fanusta yaşayabildiği söylenir ama ısıtıcısı olan, en az 15-20 litrelik bir akvaryumda çok daha uzun yaşıyor. Suyun 24-27 derece arasında tutulması gerekiyor. İşletmemizde renk seçimi yapabilirsiniz.',
    fiyat: 350,
    adet: 1,
    sehir: 'antalya',
    ilce: 'muratpasa',
    gorseller: ['HM_Orange_M_Sarawut.jpg'],
    fotografSayisi: 1,
    gorselTerimleri: ['Category:Betta splendens', 'Category:Betta', 'Siamese fighting fish'],
  },
  {
    slug: 'neon-tetra-suru',
    kullanici: 'kanatpet',
    kategori: 'akvaryum-ilanlari',
    cins: 'neon-tetra',
    kind: 'satilik',
    baslik: 'Neon tetra — on adetlik sürü hâlinde',
    aciklama:
      'Neon tetra, on adetlik gruplar hâlinde veriliyor. Karantinadan çıkmış, renkleri açık ve hareketliler.\n\nSürü balığıdır; altıdan az sayıda tutulduğunda strese giriyor ve renkleri soluyor. Bu yüzden tek tek satmıyoruz. Sakin bir türdür, agresif balıklarla aynı akvaryuma konmamalıdır. Suyun sertliği ve pH değeri konusunda kurulum önerisi veriyoruz.',
    fiyat: 600,
    adet: 10,
    sehir: 'konya',
    ilce: 'selcuklu',
    gorseller: ['Neonsalmler Paracheirodon innesi.jpg'],
    fotografSayisi: 1,
    gorselTerimleri: ['Category:Paracheirodon innesi', 'Category:Paracheirodon', 'Neon tetra fish'],
  },

  // --- Diğer ---
  {
    slug: 'tavsan-sahiplendirme-ankara',
    kullanici: 'zeynep',
    kategori: 'diger-ilanlar',
    cins: 'tavsan',
    kind: 'sahiplendirme',
    baslik: 'Bir yaşında tavşan yuva arıyor — kafesiyle birlikte',
    aciklama:
      'Bir yaşında erkek tavşan. Alışkın, elden ot ve mama alıyor, tuvaletini köşeye yapıyor. Kafes, suluk, yemlik ve saman kabı dahil veriyorum.\n\nTavşanların diş yapısı sürekli uzuyor, bu yüzden kuru ot (saman) beslenmenin temeli; sadece pelet vermek diş ve sindirim sorunlarına yol açıyor. Bunu bilerek sahiplenecek birini arıyorum. Evde küçük çocuk varsa tavşanın kucakta sıkışmaya çok hassas olduğunu hatırlatmak isterim.',
    yasAy: 12,
    cinsiyet: 'erkek',
    renk: 'Gri beyaz',
    sehir: 'ankara',
    ilce: 'cankaya',
    gorseller: ['Rabbit in hutch.jpg', 'Fluffy - the great explorer - Flickr - foshie.jpg'],
    fotografSayisi: 2,
    gorselTerimleri: ['Category:Domestic rabbits', 'Category:Oryctolagus cuniculus domesticus', 'Domestic rabbit pet'],
  },
  {
    slug: 'hamster-yavru-sahiplendirme',
    kullanici: 'burak',
    kategori: 'diger-ilanlar',
    cins: 'hamster',
    kind: 'sahiplendirme',
    baslik: 'Hamster yavruları — kafes ve çark dahil',
    aciklama:
      'Hamsterımız doğurdu, yavrular artık anneden ayrılacak yaşa geldi. Beş yavru var, hepsi sağlıklı.\n\nSuriye hamsterları yalnız yaşayan hayvanlardır; iki hamsteri aynı kafeste tutmak kavgayla sonuçlanıyor. Bu yüzden her yavru ayrı sahibe gidecek. Koşu çarkı ve kafes ilk yavruyu alacak kişiye dahil. Talaş yerine kağıt esaslı altlık kullanmanızı öneriyoruz; talaşın uçucu yağları solunum yolunu tahriş ediyor.',
    yasAy: 1,
    cinsiyet: 'belirtilmemis',
    adet: 5,
    sehir: 'bursa',
    ilce: 'nilufer',
    gorseller: ['Syrian hamster filling his cheek pouches with Dandelion leaves.JPG'],
    fotografSayisi: 1,
    gorselTerimleri: ['Category:Mesocricetus auratus', 'Category:Hamsters', 'Golden hamster'],
  },
  {
    slug: 'guineapig-cift-antalya',
    kullanici: 'akdenizpet',
    kategori: 'diger-ilanlar',
    cins: 'guineapig',
    kind: 'satilik',
    baslik: 'Guinea pig (kobay) çifti — aynı cinsiyet',
    aciklama:
      'İşletmemizde yetişen guinea piglerimiz. Aynı cinsiyette çiftler hâlinde veriyoruz.\n\nBu tür hamsterın tersine sürü hayvanıdır; tek başına tutulduğunda strese giriyor, bu yüzden en az iki olarak sahiplenilmesini öneriyoruz. Aynı cinsiyet vermemizin sebebi kontrolsüz üremeyi önlemek. Guinea pig C vitaminini kendi üretemiyor; taze biber, maydanoz gibi C vitamini kaynakları günlük beslenmenin parçası olmalı. Kurulum ve beslenme listesi veriyoruz.',
    fiyat: 1800,
    yasAy: 4,
    cinsiyet: 'belirtilmemis',
    adet: 2,
    sehir: 'antalya',
    ilce: 'muratpasa',
    gorseller: ['Two adult Guinea Pigs (Cavia porcellus).jpg'],
    fotografSayisi: 1,
    gorselTerimleri: ['Category:Cavia porcellus', 'Category:Guinea pigs', 'Guinea pig hay'],
  },
  {
    slug: 'kara-kaplumbagasi-devir',
    kullanici: 'elif',
    kategori: 'diger-ilanlar',
    cins: 'kaplumbaga',
    kind: 'sahiplendirme',
    baslik: 'Su kaplumbağası — akvaryum ve ısıtıcısıyla devir',
    aciklama:
      'Yaklaşık üç yaşında su kaplumbağası. Akvaryumu, filtresi, ısıtıcısı ve güneşlenme adasıyla birlikte devrediyorum.\n\nUzun süredir bende, sağlıklı ve iştahlı. Kabuğunda deformasyon yok. Bu hayvanlar 30 yılı aşkın yaşıyor; kısa vadeli bir karar olmadığını bilerek sahiplenmenizi rica ediyorum. UVB lambası kabuk sağlığı için gerekli, mevcut lambayı da veriyorum. Doğaya bırakmak yerine burada yuva aramamın sebebi yerli türlerin ekosistemine zarar vermemek.',
    yasAy: 36,
    cinsiyet: 'belirtilmemis',
    sehir: 'istanbul',
    ilce: 'kadikoy',
    gorseller: ['Redearedslider.jpg', 'Red Eared Slider (16430928346).jpg'],
    fotografSayisi: 2,
    gorselTerimleri: ['Category:Trachemys scripta elegans', 'Category:Trachemys scripta', 'Pond slider turtle'],
  },

  // --- Güvercin ---
  {
    slug: 'adana-taklacisi-cift',
    kullanici: 'mert',
    kategori: 'guvercin-ilanlari',
    cins: 'adana-taklacisi',
    kind: 'satilik',
    baslik: 'Adana taklacısı çift — halkalı, anaç görülür',
    aciklama:
      'Kendi kümesimde çıkan Adana taklacısı çift. Bu yılın kuşu, halkaları takılı ve numaraları ilanda paylaşılıyor. Anaçlar kümeste görülebilir.\n\nBaba hattı uzun yıllardır bende, taklası temiz ve yüksekliğini koruyor. Uçuş videosunu ilana ekledim; taklacıda fotoğraf tek başına bir şey anlatmıyor, kuşun havada ne yaptığına bakmak gerekiyor. Kuşları görmeye gelmek isteyenleri kümeste ağırlarım.',
    fiyat: 3500,
    pazarlik: true,
    yasAy: 7,
    cinsiyet: 'belirtilmemis',
    adet: 2,
    sehir: 'adana',
    ilce: 'seyhan',
    gorseller: ['Takla Tümmler.jpg'],
    fotografSayisi: 1,
    gorselTerimleri: ['Category:Tumbler pigeons', 'Category:Domestic pigeons', 'Turkish Tumbler pigeon'],
  },
  {
    slug: 'posta-guvercini-yaris-hatti',
    kullanici: 'mert',
    kategori: 'guvercin-ilanlari',
    cins: 'posta-guvercini',
    kind: 'satilik',
    baslik: 'Posta güvercini — yarış hattı, şecereli',
    aciklama:
      'Belçika hattından gelen posta güvercini. Şecere belgesi mevcut, halka numarası kayıtlı.\n\nGenç kuş; kısa mesafe antrenmanlarına başlandı, iki denemeden de yuvaya döndü. Posta güvercininde yön bulma kademeli antrenmanla oturuyor, bu yüzden ilk uçuşu uzun mesafeden yaptırmamanızı öneririm. Kuşun kendisini ve şeceresini görmek isteyenlerle görüşürüm.',
    fiyat: 5000,
    yasAy: 10,
    cinsiyet: 'erkek',
    sehir: 'adana',
    ilce: 'seyhan',
    gorseller: ['Postduif.jpg'],
    fotografSayisi: 1,
    gorselTerimleri: ['Category:Racing pigeons', 'Category:Homing pigeons', 'Racing Homer pigeon'],
  },
  {
    slug: 'sus-guvercini-koleksiyon',
    kullanici: 'mert',
    kategori: 'guvercin-ilanlari',
    cins: 'sus-guvercini',
    kind: 'satilik',
    baslik: 'Süs güvercinleri — dört adet, birlikte veya ayrı',
    aciklama:
      'Kümesimdeki süs güvercinlerinden dört adet çıkarıyorum. Hepsi bu yılın kuşu, halkalı ve sağlıklı.\n\nSüs güvercinleri uçuş için değil görünüm için tutuluyor; kanat ve kuyruk yapıları uçuşu zorlaştırdığı için kapalı kümes ve korumalı alan gerektiriyor. Kediye ve yırtıcıya karşı kümesin güvenliğine dikkat edilmeli. Birlikte de ayrı ayrı da verebilirim, görmeye gelen fiyatı beraber konuşuruz.',
    fiyat: 2000,
    pazarlik: true,
    yasAy: 6,
    adet: 4,
    sehir: 'adana',
    ilce: 'seyhan',
    gorseller: ['English pouter(brown).jpg', 'Pomeranian Pouter pigeon pair NPA National 2026 01 23.jpg'],
    fotografSayisi: 2,
    gorselTerimleri: ['Category:Fancy pigeons', 'Category:Pigeon breeds', 'Jacobin pigeon bird'],
  },
  {
    slug: 'sam-guvercini-cift',
    kullanici: 'mert',
    kategori: 'guvercin-ilanlari',
    cins: 'sam-guvercini',
    kind: 'satilik',
    baslik: 'Şam güvercini çift — kümes düzenine alışkın',
    aciklama:
      'Şam güvercini çifti. İki yaşındalar, geçen sezon yavru verdiler ve iyi anaçlık yaptılar.\n\nKümes düzenine alışkınlar, elden yem alıyorlar. İç parazit uygulaması yapıldı, solunum yolu sorunu yok. Yeni kuşu doğrudan mevcut sürünüze katmamanızı, birkaç gün ayrı kafeste gözlemenizi öneririm — bu hem sizin sürünüz hem kuş için daha güvenli. Taşıma sepeti bende mevcut.',
    fiyat: 2800,
    yasAy: 24,
    adet: 2,
    sehir: 'adana',
    ilce: 'seyhan',
    gorseller: ['Damascene(barred).jpg'],
    fotografSayisi: 1,
    gorselTerimleri: ['Category:Domestic pigeons', 'Category:Columba livia domestica', 'Domestic pigeon loft'],
  },

  // --- Pet malzemeleri ---
  {
    slug: 'ahsap-kopek-kulubesi-buyuk',
    kullanici: 'burak',
    kategori: 'pet-malzemeleri',
    cins: 'kopek-kulubesi',
    kind: 'satilik',
    baslik: 'Ahşap köpek kulübesi — büyük ırk, az kullanılmış',
    aciklama:
      'Bahçemizde bir kış kullanıldı, sonra köpeğimizi eve aldığımız için ihtiyaç kalmadı. Büyük ırk için uygun ölçüde, çatısı eğimli ve suya dayanıklı.\n\nZemin yerden yükseltilmiş, nem almıyor. Ahşabı sağlam, çürük veya kırık yok; dış cephesi geçen yıl ahşap koruyucuyla boyandı. Taşıma alıcıya ait, çok ağır değil ama tek kişiyle zor. Görmeye gelebilirsiniz.',
    fiyat: 2500,
    pazarlik: true,
    durum: 'az_kullanilmis',
    sehir: 'bursa',
    ilce: 'nilufer',
    gorseller: ['Hundehütte Hüttnerhof Rhöner Museumsdorf.JPG', 'Casa para perros.jpg'],
    fotografSayisi: 2,
    gorselTerimleri: ['Category:Dog houses', 'Category:Doghouses', 'Doghouse wooden garden'],
  },
  {
    slug: 'kedi-tirmalama-tahtasi-tirmanma',
    kullanici: 'elif',
    kategori: 'pet-malzemeleri',
    cins: 'kedi-tirmalama',
    kind: 'satilik',
    baslik: 'Kedi tırmalama ve tırmanma ünitesi — 1,5 metre',
    aciklama:
      'Bir buçuk metre yüksekliğinde tırmanma ünitesi. İki yatma platformu, bir kapalı ev ve iki sisal tırmalama direği var.\n\nKedilerimiz artık daha büyük bir üniteye geçti, bu yüzden satıyorum. Direklerin sisal halatı sağlam, sadece alt direkte hafif yıpranma var. Peluş kaplaması temiz, yıkanmış hâlde teslim ediliyor. Sökülerek taşınabiliyor, montaj çok basit. Adresimden teslim.',
    fiyat: 1200,
    pazarlik: true,
    durum: 'kullanilmis',
    sehir: 'istanbul',
    ilce: 'kadikoy',
    gorseller: ['Arbre à chat.JPG', 'Cat tree with 2 cats.jpg'],
    fotografSayisi: 2,
    gorselTerimleri: ['Category:Cat trees', 'Category:Scratching posts', 'Cat tree furniture'],
  },
  {
    slug: 'akvaryum-120-litre-set',
    kullanici: 'zeynep',
    kategori: 'pet-malzemeleri',
    cins: 'akvaryum',
    kind: 'satilik',
    baslik: '120 litre akvaryum — filtre, ısıtıcı ve dolabıyla',
    aciklama:
      '120 litrelik akvaryum, alt dolabıyla birlikte. İçten takma filtre, 200W ısıtıcı, LED aydınlatma ve termometre dahil.\n\nCam sağlam, silikonlarda kaçak yok; sökerken temizledim ve kuru olarak bekletiyorum. Dolapta küçük bir su lekesi var, fotoğrafta görünüyor. Kum ve dekor dahil değil. Bu boy bir akvaryum tek kişiyle taşınmıyor, alıcının araç ve yardımcıyla gelmesi gerekiyor.',
    fiyat: 3500,
    pazarlik: true,
    durum: 'kullanilmis',
    sehir: 'ankara',
    ilce: 'cankaya',
    gorseller: ['125L planted tank.jpg', 'Amaterske akvarium.jpg'],
    fotografSayisi: 2,
    gorselTerimleri: ['Category:Planted aquariums', 'Category:Freshwater aquaria', 'Category:Aquascaping'],
  },
  {
    slug: 'buyuk-kus-kafesi-ayakli',
    kullanici: 'mert',
    kategori: 'pet-malzemeleri',
    cins: 'kus-kafesi',
    kind: 'satilik',
    baslik: 'Ayaklı büyük kuş kafesi — papağan için uygun',
    aciklama:
      'Ayaklı, geniş kuş kafesi. Papağan ve sultan için uygun ölçüde; teller kalın ve aralıkları dar.\n\nAlt tepsi çekmeceli, temizliği kolay. Dört yemlik, iki ahşap tünek ve bir salıncak dahil. Boyasında dökülme yok, tellerde pas yok. Tekerlekli ayaklığıyla birlikte oda içinde rahat taşınıyor. Kuşlarımı dış kümese aldığım için ihtiyaç kalmadı.',
    fiyat: 1900,
    durum: 'az_kullanilmis',
    sehir: 'adana',
    ilce: 'seyhan',
    gorseller: ['Red-bellied Parrot pair in a cage.JPG', 'Aratinga canicularis - two pets in small cage-4a.jpg'],
    fotografSayisi: 2,
    gorselTerimleri: ['Category:Birdcages', 'Category:Bird cages', 'Parrot cage bird'],
  },

  // --- Kayıp ---
  {
    slug: 'kayip-tekir-kedi-kadikoy',
    kullanici: 'elif',
    kategori: 'kedi-ilanlari',
    cins: 'tekir',
    kind: 'kayip',
    olayGunOnce: 6,
    baslik: 'Kadıköy Moda\'da tekir kedimiz kayboldu',
    aciklama:
      'Kedimiz altı gün önce balkon kapısı açık kalınca çıktı ve dönmedi. Moda sahil çevresinde, Bahariye tarafında görülmüş olabilir.\n\nTekir desenli, karnı beyaz, boynunda mavi tasma vardı ama tasması düşmüş olabilir. Yaklaşık üç yaşında, kısırlaştırılmış ve mikroçipli. Ürkek bir kedi, seslenince yaklaşmaz; gördüyseniz kovalamayın, lütfen bize haber verin.\n\nAyırt edici bir işareti daha var, onu ilanda yazmıyoruz — arayan kişiden sormamız için. Bulan kişiye teşekkür ederiz.',
    yasAy: 36,
    cinsiyet: 'disi',
    renk: 'Tekir',
    kisir: true,
    mikrocip: true,
    sehir: 'istanbul',
    ilce: 'kadikoy',
    gorseller: ['Cat in İzmir (04092026) 01.jpg'],
    fotografSayisi: 1,
    gorselTerimleri: ['Category:Tabby cats'],
  },
  {
    slug: 'kayip-melez-kopek-cankaya',
    kullanici: 'zeynep',
    kategori: 'kopek-ilanlari',
    cinsDiger: 'Melez',
    kind: 'kayip',
    olayGunOnce: 3,
    baslik: 'Çankaya\'da köpeğimiz tasmasından kurtulup kaçtı',
    aciklama:
      'Akşam yürüyüşünde havai fişek sesinden ürküp tasmasından sıyrıldı ve koştu. Ayrancı çevresinde kayboldu, üç gündür arıyoruz.\n\nOrta boy, sarı-beyaz tüylü, kuyruğu kıvrık. Kırmızı göğüs tasması üzerindeydi, künyesinde telefon numarası yazıyor. Mikroçipli; bulup veterinere götürürseniz kaydımıza ulaşabilirsiniz.\n\nİnsana alışkın ama korktuğu için saklanıyor olabilir. Otopark, bodrum ve inşaat alanlarına bakmanızı rica ediyoruz.',
    yasAy: 48,
    cinsiyet: 'erkek',
    boyut: 'orta',
    renk: 'Sarı beyaz',
    asili: true,
    kisir: true,
    mikrocip: true,
    sehir: 'ankara',
    ilce: 'cankaya',
    gorseller: ['Street dog 03617.JPG'],
    fotografSayisi: 1,
    gorselTerimleri: ['Category:Dogs of Turkey'],
  },
  {
    slug: 'kayip-muhabbet-kusu-karsiyaka',
    kullanici: 'burak',
    kategori: 'kus-ilanlari',
    cins: 'muhabbet-kusu',
    kind: 'kayip',
    olayGunOnce: 2,
    baslik: 'Muhabbet kuşumuz pencereden uçtu — Karşıyaka',
    aciklama:
      'Kafesini temizlerken pencere açıktı, iki gün önce uçup gitti. Bostanlı çevresinde, sahil bandındaki ağaçlarda olabilir.\n\nMavi-beyaz renkli, ayağında halka var. Elde büyüdüğü için insandan kaçmıyor; balkona konarsa yem koyup kapıyı açık bırakırsanız içeri girebilir.\n\nAdını duyunca ses veriyor. Gören olursa haber vermenizi rica ediyoruz.',
    yasAy: 14,
    cinsiyet: 'erkek',
    renk: 'Mavi beyaz',
    sehir: 'izmir',
    ilce: 'karsiyaka',
    gorseller: ['Budgie (8022436701).jpg'],
    fotografSayisi: 1,
    gorselTerimleri: ['Category:Melopsittacus undulatus'],
  },
  {
    slug: 'kayip-posta-guvercini-seyhan',
    kullanici: 'mert',
    kategori: 'guvercin-ilanlari',
    cins: 'posta-guvercini',
    kind: 'kayip',
    olayGunOnce: 9,
    baslik: 'Antrenmandan dönmeyen posta güvercini — halka numarası var',
    aciklama:
      'Dokuz gün önceki antrenman uçuşundan dönmedi. Genç kuş, uzun mesafe deneyimi yok; yorulup bir kümese ya da çatıya konmuş olabilir.\n\nAyağında kayıtlı halka var, numarası bende. Kuşu bulan bir yetiştirici arkadaş halkadan bana ulaşabilir. Yem ve su verip birkaç gün tutarsanız toparlanır.\n\nSeyhan ve çevresindeki kümes sahiplerinin haberdar olması için ilan veriyorum. Bulana emeğinin karşılığını veririm.',
    yasAy: 8,
    cinsiyet: 'erkek',
    sehir: 'adana',
    ilce: 'seyhan',
    gorselTerimleri: ['Category:Racing pigeons', 'Category:Homing pigeons'],
    fotografSayisi: 1,
  },

  // --- Bulundu ---
  {
    slug: 'bulunan-kedi-nilufer',
    kullanici: 'burak',
    kategori: 'kedi-ilanlari',
    cins: 'tekir',
    kind: 'bulundu',
    olayGunOnce: 4,
    baslik: 'Nilüfer\'de bakımlı bir kedi bulduk, sahibi aranıyor',
    aciklama:
      'Dört gün önce apartman girişinde buldum. Bakımlı, tüyleri temiz ve insana çok alışkın — sokak kedisi değil, kaybolmuş bir ev kedisi olduğu belli.\n\nVeterinere götürüp mikroçip taratmak istedim ama çipi yok. Sağlıklı, aşı durumu bilinmiyor. Şu an bende kalıyor, kedime yakın davranıyor.\n\nSahibiyseniz kedinin ayırt edici bir özelliğini ve nerede kaybolduğunu söylemenizi rica edeceğim; ilanda bu ayrıntıları yazmadım.',
    yasAy: 24,
    cinsiyet: 'belirtilmemis',
    renk: 'Tekir',
    sehir: 'bursa',
    ilce: 'nilufer',
    gorseller: ['Cat in İzmir (04092026) 03.jpg'],
    fotografSayisi: 1,
    gorselTerimleri: ['Category:Tabby cats'],
  },
  {
    slug: 'bulunan-tasmali-kopek-muratpasa',
    kullanici: 'akdenizpet',
    kategori: 'kopek-ilanlari',
    cinsDiger: 'Melez',
    kind: 'bulundu',
    olayGunOnce: 2,
    baslik: 'İşletmemizin önünde tasmalı bir köpek bulduk',
    aciklama:
      'İki gün önce dükkânın önünde bekliyordu. Tasması var ama künyesi yok. Aç ve susamıştı, mama ve su verdik.\n\nMikroçip taraması yaptırdık, çip çıkmadı. Yaklaşık dört yaşında, orta boy, uysal bir köpek. Eğitimli; oturma komutunu biliyor, bu da bakımlı bir evden geldiğini gösteriyor.\n\nSahibi çıkana kadar işletmemizde bakıyoruz. Muratpaşa çevresinde köpeğini kaybeden varsa bize ulaşsın.',
    yasAy: 48,
    cinsiyet: 'erkek',
    boyut: 'orta',
    renk: 'Kahverengi',
    sehir: 'antalya',
    ilce: 'muratpasa',
    gorseller: ['A dog in Amasra - 02.jpg'],
    fotografSayisi: 1,
    gorselTerimleri: ['Category:Dogs of Turkey'],
  },
  {
    slug: 'bulunan-yavru-kedi-selcuklu',
    kullanici: 'kanatpet',
    kategori: 'kedi-ilanlari',
    cins: 'tekir',
    kind: 'bulundu',
    olayGunOnce: 5,
    baslik: 'Yavru kedi bulundu — annesini arıyor olabilir',
    aciklama:
      'Dükkânın arkasındaki bahçede tek başına miyavlarken bulduk. Yaklaşık iki aylık, annesi çevrede görünmüyor.\n\nVeterinere götürdük; sağlıklı, iç parazit uygulaması yapıldı. Mama yiyor ve kum kabını kullanıyor.\n\nEvinden kaçmış olma ihtimaline karşı ilan veriyoruz. Bir hafta içinde sahibi çıkmazsa sahiplendireceğiz; sahiplenmek isteyenler de yazabilir.',
    yasAy: 2,
    cinsiyet: 'belirtilmemis',
    renk: 'Tekir',
    icParazit: true,
    sehir: 'konya',
    ilce: 'selcuklu',
    gorseller: ['CatInBox.jpg'],
    fotografSayisi: 1,
    gorselTerimleri: ['Category:Kittens'],
  },
  {
    slug: 'bulunan-golden-atakum',
    kullanici: 'zeynep',
    kategori: 'kopek-ilanlari',
    cins: 'golden-retriever',
    kind: 'bulundu',
    olayGunOnce: 1,
    baslik: 'Sahilde başıboş dolaşan Golden Retriever bulundu',
    aciklama:
      'Dün akşam sahil yürüyüş yolunda tek başına dolaşıyordu. Boynunda tasma vardı, künye yok.\n\nÇok uysal ve insana alışkın, kesinlikle bir evin köpeği. Tüyleri bakımlı, tırnakları kesilmiş. Yaklaşık üç yaşında görünüyor.\n\nGeceyi bizde geçirdi. Sabah veterinere götürüp çip taratacağım; çip çıkmazsa sahibinin bu ilanı görmesini umuyorum. Atakum çevresinde köpeğini kaybeden varsa ulaşsın.',
    yasAy: 36,
    cinsiyet: 'erkek',
    boyut: 'buyuk',
    renk: 'Krem',
    sehir: 'samsun',
    ilce: 'atakum',
    gorseller: ['A Golden Retriever-5 (Barras).JPG'],
    fotografSayisi: 1,
    gorselTerimleri: ['Category:Golden Retriever'],
  },

  // --- Eş arayan ---
  {
    slug: 'es-arayan-golden-disi',
    kullanici: 'anadolu',
    kategori: 'kopek-ilanlari',
    cins: 'golden-retriever',
    kind: 'es_arayan',
    baslik: 'Şecereli Golden Retriever dişimize eş arıyoruz',
    aciklama:
      'Tesisimizdeki üç yaşındaki dişi Golden Retriever için uygun eş arıyoruz. Kalça ve dirsek skoru belgeli, göz muayenesi güncel.\n\nAdayın da kalça-dirsek skorunun belgeli olmasını, kalıtsal göz hastalıkları açısından taranmış olmasını istiyoruz. Bu ırkta eklem sorunları yaygın; belgesiz eşleştirme sorunu bir sonraki kuşağa taşıyor.\n\nÜretim iznimiz mevcut. Şartları ve şecereleri karşılıklı paylaşarak konuşalım.',
    yasAy: 36,
    cinsiyet: 'disi',
    boyut: 'buyuk',
    renk: 'Krem',
    asili: true,
    secere: true,
    mikrocip: true,
    saglikRaporu: true,
    sehir: 'sivas',
    ilce: 'merkez',
    gorseller: ['A Golden Retriever-2 (Barras).JPG'],
    fotografSayisi: 1,
    gorselTerimleri: ['Category:Golden Retriever'],
  },
  {
    slug: 'es-arayan-british-shorthair',
    kullanici: 'egekatteri',
    kategori: 'kedi-ilanlari',
    cins: 'british-shorthair',
    kind: 'es_arayan',
    baslik: 'British Shorthair erkeğimize HCM taramalı eş arıyoruz',
    aciklama:
      'Katterimizdeki iki yaşındaki British Shorthair erkek için eş arıyoruz. Kalp taraması (HCM ekokardiyografi) yapıldı, sonucu temiz; belgesi mevcut.\n\nAdayın da HCM taramasının yapılmış olmasını şart koşuyoruz. Bu ırkta kalp kası kalınlaşması belirti vermeden ilerleyebiliyor; taramasız eşleştirme riski yavrulara aktarıyor.\n\nKan grubu uyumu için de test isteyeceğiz: B grubu bu ırkta sık görülüyor ve uyumsuz eşleştirme yenidoğan kayıplarına yol açıyor. Şecere ve test belgelerini karşılıklı paylaşarak görüşelim.',
    yasAy: 24,
    cinsiyet: 'erkek',
    renk: 'Gri (blue)',
    asili: true,
    secere: true,
    mikrocip: true,
    saglikRaporu: true,
    sehir: 'izmir',
    ilce: 'karsiyaka',
    gorseller: ['British Shorthair. Female. 18 months old.jpg'],
    gorselTerimleri: ['Category:British Shorthair'],
    fotografSayisi: 1,
  },
  {
    slug: 'es-arayan-taklaci-guvercin',
    kullanici: 'mert',
    kategori: 'guvercin-ilanlari',
    cins: 'adana-taklacisi',
    kind: 'es_arayan',
    baslik: 'Taklacı erkeğime aynı hattan dişi arıyorum',
    aciklama:
      'Kümesimdeki taklacı erkek için eş arıyorum. İki yaşında, taklası temiz ve yüksekliğini koruyor; uçuş videosunu paylaşabilirim.\n\nAynı hattan ya da uyumlu bir hattan dişi arıyorum. Anaç bilgisi ve halka numarası olan kuşlarla ilgileniyorum; halkasız kuşta yaş ve köken beyandan ibaret kalıyor.\n\nKuşları önce görüşüp kümeste tanıştıralım. Adana ve çevresindeki yetiştiricilerle görüşmek isterim.',
    yasAy: 24,
    cinsiyet: 'erkek',
    sehir: 'adana',
    ilce: 'seyhan',
    gorseller: ['Takla Tümmler.jpg'],
    gorselTerimleri: ['Category:Tumbler pigeons', 'Category:Racing pigeons'],
    fotografSayisi: 1,
  },
  {
    slug: 'es-arayan-sultan-papagani',
    kullanici: 'zeynep',
    kategori: 'kus-ilanlari',
    cins: 'sultan-papagani',
    kind: 'es_arayan',
    baslik: 'Sultan papağanı dişimize eş arıyoruz',
    aciklama:
      'İki yaşındaki dişi sultan papağanımız için eş arıyoruz. Sağlıklı, tüyleri düzgün, iştahı yerinde.\n\nYalnız kalmaktan hoşlanmıyor; bu tür sürü hâlinde yaşıyor ve tek başına tutulduğunda tüy yolma davranışı gelişebiliyor. Bu yüzden kalıcı bir eş arıyoruz.\n\nAdayın veteriner kontrolünden geçmiş olmasını rica ediyoruz. Kuşları önce ayrı kafeslerde yan yana tutarak alıştırmayı, sonra birleştirmeyi düşünüyoruz.',
    yasAy: 24,
    cinsiyet: 'disi',
    sehir: 'ankara',
    ilce: 'cankaya',
    gorselTerimleri: ['Category:Nymphicus hollandicus', 'Category:Cockatiels'],
    fotografSayisi: 1,
  },
];
